repos:
  - repo: local
    hooks:
      - id: format
        name: Ruff formatter
        entry: .venv/bin/ruff format --check # Ruff installed by uv
        language: system
        types: [python]
      - id: lint
        name: Ruff linter
        entry: .venv/bin/ruff check # Ruff installed by uv
        language: system
        types: [python]
        # While it's not efficient, and generally is not necessary,
        # It's a bit more robust to run ruff on the entire project
        # rather than just the changed files.
        pass_filenames: false
        always_run: true
      - id: typing
        name: MyPy type checker
        entry: .venv/bin/mypy
        language: system
        types: [python]
        exclude: ^(examples/|docs/)
